import { BUILDER_CATALOG } from './catalog'
import type { BuilderDocument, BuilderNode } from './schema'

const BASE_UIKIT_COMPONENTS = new Set([
  'base',
  'button',
  // The generated application baseline is imported by `_import.less`; card
  // is intentionally owned there so published pages do not emit it twice.
  'card',
  'close',
  'container',
  'flex',
  'form',
  'form-range',
  'grid',
  'heading',
  'height',
  'icon',
  'inverse',
  'link',
  'margin',
  'modal',
  'nav',
  'navbar',
  'padding',
  'position',
  'section',
  'text',
  'tooltip',
  'utility',
  'visibility',
  'width',
])

function visit(nodes: BuilderNode[], components: Set<string>): void {
  for (const node of nodes) {
    BUILDER_CATALOG[node.type].uikitComponents.forEach((component) => components.add(component))
    visit(node.children, components)
  }
}

export function getBuilderUIKitComponents(document: BuilderDocument): string[] {
  const components = new Set<string>()
  visit(document.nodes, components)
  return [...components].sort()
}

export function generateBuilderComponentLess(document: BuilderDocument): string {
  const imports = getBuilderUIKitComponents(document)
    .filter((component) => !BASE_UIKIT_COMPONENTS.has(component))
    .map(
      (component) => `@import '../../../node_modules/uikit/src/less/components/${component}.less';`,
    )
    .join('\n')

  return [
    '// Generated by /admin/. Do not edit by hand.',
    '// Only UIkit components required by saved builder documents are emitted here.',
    imports ||
      '// The current builder document needs no components beyond the application baseline.',
    '',
  ].join('\n')
}

export function generateBuilderThemeLess(document: BuilderDocument): string {
  const { theme } = document
  const shadows = {
    none: 'none',
    soft: '0 8px 24px rgba(0, 0, 0, 0.22)',
    deep: '0 20px 56px rgba(0, 0, 0, 0.42)',
  } as const
  const cardShadow = shadows[theme.cardShadow as keyof typeof shadows] ?? shadows.deep
  return [
    '// Generated by /admin/. Do not edit by hand.',
    '// Strict document validation prevents arbitrary Less from entering this file.',
    `@jlz-color-accent: ${theme.accent};`,
    `@jlz-color-accent-hover: ${theme.accentHover};`,
    `@jlz-color-accent-secondary: ${theme.accentSecondary};`,
    `@jlz-color-bg: ${theme.background};`,
    `@jlz-color-bg-elevated: ${theme.backgroundElevated};`,
    `@jlz-color-surface: ${theme.surface};`,
    `@jlz-color-surface-hover: ${theme.surfaceHover};`,
    `@jlz-color-text: ${theme.text};`,
    `@jlz-color-text-muted: ${theme.textMuted};`,
    `@jlz-color-border: ${theme.border};`,
    `@jlz-color-border-strong: ${theme.border};`,
    `@jlz-color-signal-cool: ${theme.signalCool};`,
    `@jlz-color-signal-ember: ${theme.signalEmber};`,
    `@jlz-inverse-bg: ${theme.inverseBackground};`,
    `@jlz-inverse-surface: ${theme.inverseSurface};`,
    `@jlz-inverse-text: ${theme.inverseText};`,
    `@jlz-inverse-text-muted: ${theme.inverseTextMuted};`,
    `@jlz-inverse-accent: ${theme.inverseAccent};`,
    `@jlz-radius-md: ${theme.radius};`,
    `@jlz-radius-lg: ${theme.radius};`,
    `@jlz-button-radius: ${theme.buttonRadius};`,
    `@jlz-card-radius: ${theme.cardRadius};`,
    `@jlz-card-shadow: ${cardShadow};`,
    `@jlz-form-border: ${theme.formBorder};`,
    `@jlz-navbar-surface: ${theme.navbarSurface};`,
    `@global-font-size: ${theme.fontSize};`,
    `@global-line-height: ${theme.lineHeight};`,
    `@global-margin: ${theme.spacing};`,
    `@global-small-margin: (${theme.spacing} * 0.6);`,
    `@global-gutter: ${theme.gridGutter};`,
    `@global-small-gutter: (${theme.gridGutter} * 0.75);`,
    `@global-link-color: ${theme.linkColor};`,
    `@link-muted-color: ${theme.linkMutedColor};`,
    `@list-margin-top: ${theme.listGap};`,
    `@base-hr-border: ${theme.dividerColor};`,
    `@base-hr-margin-vertical: ${theme.dividerSpacing};`,
    `@global-control-height: ${theme.controlHeight};`,
    `@global-primary-font-weight: ${theme.headingWeight};`,
    `@base-heading-text-transform: ${theme.headingTransform};`,
    `@button-line-height: ${theme.buttonHeight};`,
    `@button-font-weight: ${theme.buttonWeight};`,
    `@button-text-transform: ${theme.buttonTransform};`,
    `@card-body-padding-horizontal: ${theme.cardPadding};`,
    `@card-body-padding-vertical: ${theme.cardPadding};`,
    `@section-muted-background: ${theme.sectionMuted};`,
    `@section-primary-background: ${theme.sectionPrimary};`,
    `@section-secondary-background: ${theme.sectionSecondary};`,
    `@form-height: ${theme.controlHeight};`,
    `@form-background: ${theme.formSurface};`,
    `@navbar-nav-item-height: ${theme.navbarHeight};`,
    `@navbar-background: ${theme.navbarSurface};`,
    '',
  ].join('\n')
}
