#!/usr/bin/env bun

/**
 * Generate source-module profiles for the delivery-critical vendor chunks:
 * the shared Three.js chunk (`vendor-three`) and the lazy Cientos/camera-
 * controls ecosystem chunk (`vendor-lab-controls`). One sourcemapped build,
 * one report per chunk, run-unique filenames under docs/evidence/bundle-
 * breakdown/ (see that directory's README for the protocol).
 */
import { execFileSync } from 'node:child_process'
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs'
import { join, resolve } from 'node:path'
import { SourceMapConsumer, type RawSourceMap } from 'source-map-js'
import { sharedThreeAsset } from './build-assets'

const root = resolve(import.meta.dir, '..')
const tempDir = resolve('/tmp', 'jlz-bundle-breakdown-' + process.pid)
const assetsDir = join(tempDir, 'assets')
const commit = execFileSync('git', ['rev-parse', 'HEAD'], {
  cwd: root,
  encoding: 'utf8',
}).trim()

const generatedAt = new Date().toISOString()
const dirtyFiles = execFileSync('git', ['status', '--porcelain'], {
  cwd: root,
  encoding: 'utf8',
})
  .trim()
  .split('\n')
  .filter(Boolean)

/** Map generated bytes of one built chunk back to its source modules. */
function profileChunk(jsFile: string): {
  chunk: string
  rawBytes: number
  sourceCount: number
  modules: { source: string; mappedBytes: number }[]
} {
  const mapPath = join(assetsDir, jsFile + '.map')
  if (!existsSync(mapPath)) throw new Error('source map not found: ' + mapPath)
  const sourceMap = JSON.parse(readFileSync(mapPath, 'utf8')) as RawSourceMap
  const sourceBytes = new Map<string, number>()
  const mapped = new SourceMapConsumer(sourceMap)
  const lines = readFileSync(join(assetsDir, jsFile), 'utf8').split('\n')
  const byLine = new Map<number, { column: number; source: string }[]>()
  mapped.eachMapping((item) => {
    if (!item.source) return
    const line = byLine.get(item.generatedLine) || []
    line.push({ column: item.generatedColumn, source: item.source })
    byLine.set(item.generatedLine, line)
  })
  for (const [lineNumber, points] of byLine) {
    points.sort((a, b) => a.column - b.column)
    const line = lines[lineNumber - 1] ?? ''
    const lineLength = line.length
    points.forEach((point, index) => {
      const end = points[index + 1] ? points[index + 1].column : lineLength
      sourceBytes.set(
        point.source,
        (sourceBytes.get(point.source) || 0) + Buffer.byteLength(line.slice(point.column, end)),
      )
    })
  }
  return {
    chunk: jsFile,
    rawBytes: statSync(join(assetsDir, jsFile)).size,
    sourceCount: sourceBytes.size,
    modules: [...sourceBytes.entries()]
      .map(([source, mappedBytes]) => ({ source, mappedBytes }))
      .sort((a, b) => b.mappedBytes - a.mappedBytes),
  }
}

rmSync(tempDir, { recursive: true, force: true })
mkdirSync(tempDir, { recursive: true })

try {
  execFileSync('bun', ['x', 'vite', 'build', '--sourcemap', '--outDir', tempDir], {
    cwd: root,
    stdio: 'inherit',
  })
  const assetNames = readdirSync(assetsDir)
  // The shared Three.js chunk is selected by the delivery contract
  // (excludes the Contact addon chunks); the lab-controls chunk is the
  // single file its rollup group rule names.
  const threeAsset = sharedThreeAsset(assetNames)
  const labAssets = assetNames.filter((name) => /^vendor-lab-controls-.*\.js$/.test(name))
  if (labAssets.length !== 1) {
    throw new Error(`Expected one vendor-lab-controls asset, found ${labAssets.length}`)
  }
  const targets: { label: string; jsFile: string }[] = [
    { label: 'vendor-three', jsFile: threeAsset },
    { label: 'vendor-lab-controls', jsFile: labAssets[0]! },
  ]

  const destinationDir = resolve(root, 'docs/evidence/bundle-breakdown')
  mkdirSync(destinationDir, { recursive: true })
  for (const { label, jsFile } of targets) {
    const profile = profileChunk(jsFile)
    const report = {
      commit,
      generatedAt,
      dirtyFiles,
      command: 'bun scripts/bundle-breakdown.ts',
      note: 'Source-mapped analysis build; production gzip budgets are checked separately.',
      ...profile,
    }
    const destination = join(
      destinationDir,
      `${commit.slice(0, 7)}-${generatedAt.replace(/[:.]/g, '-')}-${label}.json`,
    )
    writeFileSync(destination, JSON.stringify(report, null, 2) + '\n', { flag: 'wx' })
    console.log(`Wrote ${destination} (${profile.sourceCount} sources)`)
  }
} finally {
  rmSync(tempDir, { recursive: true, force: true })
}
